#!/bin/bash
set -e

OUTPUT_DIR="$1"
COMMIT_OVERRIDE="$2"  # Optional commit SHA

if [ -z "$OUTPUT_DIR" ]; then
    echo "Usage: $0 <output-directory-wsl-path>"
    exit 1
fi

REPO_URL="https://github.com/alesimula/Murine-launcher"
RAW_URL="https://raw.githubusercontent.com/alesimula/Murine-launcher"

# --- Step 1: Determine which commit to use ---
if [ -n "$COMMIT_OVERRIDE" ]; then
    COMMIT="$COMMIT_OVERRIDE"
    echo "==> Using provided commit: $COMMIT"
else
    echo "==> Fetching latest commit from GitHub..."
    COMMIT=$(git ls-remote "$REPO_URL" HEAD | awk '{print $1}')

    if [ -z "$COMMIT" ]; then
        echo "ERROR: Failed to fetch latest commit SHA"
        exit 1
    fi
    echo "    Latest commit: $COMMIT"
fi

# --- Step 2: Fetch versionName and versionCode from build.gradle in that tree ---
echo "==> Fetching build.gradle from commit $COMMIT..."
BUILD_GRADLE=$(curl -sL "$RAW_URL/$COMMIT/build.gradle")

if [ -z "$BUILD_GRADLE" ]; then
    echo "ERROR: Failed to fetch build.gradle from GitHub"
    exit 1
fi

VERSION_CODE=$(echo "$BUILD_GRADLE" | grep -m1 'versionCode ' | sed 's/.*versionCode\s*\([0-9]\+\).*/\1/')
VERSION_NAME=$(echo "$BUILD_GRADLE" | grep -m1 'versionName ' | sed 's/.*versionName\s*["'\''"]*\([^"'\''"]*\).*/\1/')

if [ -z "$VERSION_CODE" ] || [ -z "$VERSION_NAME" ]; then
    echo "ERROR: Failed to parse version from build.gradle"
    echo "  versionCode=$VERSION_CODE versionName=$VERSION_NAME"
    exit 1
fi
echo "    versionCode: $VERSION_CODE"
echo "    versionName: $VERSION_NAME"

# --- Step 3: Update fdroid metadata (commit, versionName, versionCode inside Builds) ---
META="$HOME/fdroiddata/metadata/app.murinelauncher.yml"
if [ ! -f "$META" ]; then
    echo "ERROR: Metadata file not found: $META"
    exit 1
fi

sed -i "s/^\(\s*\(-\s*\)\?commit:\s*\).*/\1$COMMIT/" "$META"
sed -i "s/^\(\s*\(-\s*\)\?versionCode:\s*\).*/\1$VERSION_CODE/" "$META"
sed -i "s/^\(\s*\(-\s*\)\?versionName:\s*\).*/\1'$VERSION_NAME'/" "$META"
echo "==> Updated metadata: commit, versionName, versionCode"

# --- Step 4: Clean previous unsigned artifacts for this versionCode ---
UNSIGNED_DIR="$HOME/fdroiddata/unsigned"
for f in "$UNSIGNED_DIR"/app.murinelauncher_${VERSION_CODE}.*; do
    if [ -f "$f" ]; then
        echo "    Removing old artifact: $f"
        rm -f "$f"
    fi
done

# --- Step 5: Run fdroid build inside Docker ---
# fdroid may return non-zero from binary comparison even on a successful build,
# so the build just relies on APK freshness on step 6.
echo "==> Starting Docker fdroid build..."
set +e
docker run --rm -u vagrant --entrypoint /bin/bash \
  -v ~/fdroiddata:/build:z \
  -v ~/fdroidserver:/home/vagrant/fdroidserver:Z \
  registry.gitlab.com/fdroid/fdroidserver:buildserver \
  -c '. /etc/profile
export PATH="$fdroidserver:$PATH" PYTHONPATH="$fdroidserver"
export JAVA_HOME=$(java -XshowSettings:properties -version 2>&1 > /dev/null | grep "java.home" | awk -F"=" "{print \$2}" | tr -d " ")
cd /build
fdroid readmeta
fdroid rewritemeta app.murinelauncher
fdroid checkupdates --allow-dirty app.murinelauncher
fdroid lint app.murinelauncher
fdroid build app.murinelauncher
exit'
DOCKER_EXIT=$?
set -e
echo "==> Docker exited with code $DOCKER_EXIT"

# --- Step 6: Copy APK to output directory (with freshness check) ---
APK="$HOME/fdroiddata/build/app.murinelauncher/build/outputs/apk/aospWithoutQuickstep/release/app.murinelauncher-aosp-withoutQuickstep-release-unsigned.apk"
if [ -f "$APK" ]; then
    APK_MTIME=$(stat -c %Y "$APK")
    NOW=$(date +%s)
    AGE=$(( NOW - APK_MTIME ))
    if [ "$AGE" -gt 10 ]; then
        echo "WARNING: APK exists but was last modified ${AGE}s ago (>10s)."
        echo "         It may not have been generated by this build."
        echo "         Path: $APK"
        exit 1
    fi
    cp "$APK" "$OUTPUT_DIR/"
    echo "==> SUCCESS (ignore error messages): APK copied to $OUTPUT_DIR/ (modified ${AGE}s ago)"
else
    echo "ERROR: APK not found at expected path:"
    echo "  $APK"
    echo "Listing available files under build output dir:"
    find "$HOME/fdroiddata/build/app.murinelauncher/build/outputs/" -name "*.apk" 2>/dev/null || echo "  (no apk files found)"
    exit 1
fi
